name: Bikin APK Fish It

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # Node.js tetep 22 biar Capacitor seneng
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Clean & Install Dependencies
        run: |
          rm -rf node_modules
          rm -f package-lock.json
          npm install

      - name: Sync Capacitor
        run: npx cap sync android

      # --- INI YANG KITA UBAH (17 -> 21) ---
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21' # Ganti ke 21 biar Gradle 8.14 seneng

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Fix Permissions & Build APK
        run: |
          cd android
          chmod +x gradlew
          bash ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: FishIt-Ultra-APK
          path: android/app/build/outputs/apk/debug/app-debug.apk